name: Teste_ci/cd
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4

     - name: Contentful
       run: echo "${{ secrets.CONTENTFUL }}" > .env
     
     - name: Ci  
       run: npm ci

     - name: Lint
       run: npm run lint
    
     - name: Format  
       run: npm run format
       if: success()

     - name: Test  
       run: npm run test
       if: success()

     - name: Build
       run: npm run build
       if: success()

     - name: Deploy
       run: npx netlify-cli deploy --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --prod
       if: success()